create type public.idea_status as enum (
  'draft',
  'published',
  'funding',
  'funded',
  'in_progress',
  'completed',
  'cancelled'
);

create type public.idea_media_kind as enum ('image', 'video');

create table public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint categories_slug_format check (
    slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    and char_length(slug) between 2 and 60
  ),
  constraint categories_name_length check (char_length(name) between 2 and 80),
  constraint categories_description_length check (
    description is null or char_length(description) <= 500
  )
);

create table public.ideas (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references public.profiles (id) on delete cascade,
  category_id bigint references public.categories (id) on delete set null,
  slug text not null unique,
  title text not null,
  summary text not null,
  description text not null,
  status public.idea_status not null default 'draft',
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint ideas_slug_format check (
    slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    and char_length(slug) between 3 and 100
  ),
  constraint ideas_title_length check (char_length(title) between 3 and 120),
  constraint ideas_summary_length check (char_length(summary) between 10 and 280),
  constraint ideas_description_length check (
    char_length(description) between 20 and 20000
  )
);

create index ideas_creator_id_idx on public.ideas (creator_id);
create index ideas_category_id_idx on public.ideas (category_id);
create index ideas_status_published_at_idx
on public.ideas (status, published_at desc)
where status <> 'draft';

create table public.idea_media (
  id uuid primary key default gen_random_uuid(),
  idea_id uuid not null references public.ideas (id) on delete cascade,
  kind public.idea_media_kind not null,
  url text not null,
  alt_text text,
  sort_order smallint not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  constraint idea_media_url_format check (
    url ~* '^https?://'
    and char_length(url) <= 2048
  ),
  constraint idea_media_alt_text_length check (
    alt_text is null or char_length(alt_text) <= 300
  ),
  constraint idea_media_sort_order_nonnegative check (sort_order >= 0),
  constraint idea_media_idea_sort_order_unique unique (idea_id, sort_order)
);

create index idea_media_idea_id_idx on public.idea_media (idea_id);

comment on table public.categories is
  'Curated public categories used to organize ideas.';
comment on table public.ideas is
  'Creator-owned ideas and their publication lifecycle state.';
comment on table public.idea_media is
  'Ordered image and video references belonging to an idea.';

create function public.set_idea_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

revoke all on function public.set_idea_updated_at() from public;

create trigger set_ideas_updated_at
before update on public.ideas
for each row execute function public.set_idea_updated_at();

alter table public.categories enable row level security;
alter table public.ideas enable row level security;
alter table public.idea_media enable row level security;

create policy "Categories are viewable by everyone"
on public.categories
for select
to anon, authenticated
using (true);

create policy "Published ideas are viewable by everyone"
on public.ideas
for select
to anon, authenticated
using (status <> 'draft' or (select auth.uid()) = creator_id);

create policy "Creators can create ideas"
on public.ideas
for insert
to authenticated
with check ((select auth.uid()) = creator_id);

create policy "Creators can update their ideas"
on public.ideas
for update
to authenticated
using ((select auth.uid()) = creator_id)
with check ((select auth.uid()) = creator_id);

create policy "Creators can delete their ideas"
on public.ideas
for delete
to authenticated
using ((select auth.uid()) = creator_id);

create policy "Published idea media is viewable by everyone"
on public.idea_media
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.ideas
    where ideas.id = idea_media.idea_id
      and (ideas.status <> 'draft' or (select auth.uid()) = ideas.creator_id)
  )
);

create policy "Creators can manage their idea media"
on public.idea_media
for all
to authenticated
using (
  exists (
    select 1
    from public.ideas
    where ideas.id = idea_media.idea_id
      and (select auth.uid()) = ideas.creator_id
  )
)
with check (
  exists (
    select 1
    from public.ideas
    where ideas.id = idea_media.idea_id
      and (select auth.uid()) = ideas.creator_id
  )
);

revoke all on table public.categories from anon, authenticated;
revoke all on table public.ideas from anon, authenticated;
revoke all on table public.idea_media from anon, authenticated;

grant select on table public.categories to anon, authenticated;
grant select on table public.ideas to anon, authenticated;
grant select on table public.idea_media to anon, authenticated;
grant insert, update, delete on table public.ideas to authenticated;
grant insert, update, delete on table public.idea_media to authenticated;
